version: '2'
volumes:
  ssh-data: {}
services:
  mesosbase:
    build: ../yelp_package/dockerfiles/itest/mesos/
  mesosmaster:
    build: ../yelp_package/dockerfiles/mesos-paasta/
    ports:
      - '5050:5050'
      - '5054:5054'
      - 22
    depends_on:
      - mesosbase
      - zookeeper
    volumes:
      - /var/tmp/pip_cache1:/var/tmp/pip_cache
      - ../:/work:rw
      - ./paasta:/etc/paasta:rw
      - ./example-services:/nail/etc/services:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh-data:/root/.ssh
    command: '/start.sh'
  mesosslave:
    ports:
      - 5051
      - 22
    build: ../yelp_package/dockerfiles/mesos-paasta/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh-data:/root/.ssh
    depends_on:
      - mesosbase
      - zookeeper
    command: '/start-slave.sh'
  marathon:
    ports:
      - '8080:8080'
    depends_on:
      - zookeeper
  itest_trusty:
    build: ../yelp_package/dockerfiles/trusty/
  playground:
    build: ../yelp_package/dockerfiles/playground/
    volumes:
      - /var/tmp/pip_cache2:/var/tmp/pip_cache
      - ../:/work:rw
      - ./paasta:/etc/paasta:rw
      - ./example-services:/nail/etc/services:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - ssh-data:/root/.ssh
    command: '/start.sh'
    depends_on:
      - mesosmaster
      - itest_trusty
      - chronos
      - registry
      - git
      - mesosslave
      - marathon
  chronos:
    ports:
      - '8081:8081'
    depends_on:
      - zookeeper
  registry:
    image: registry:2
    ports:
      - '5000:5000'
  git:
    build: ../yelp_package/dockerfiles/gitremote/
    command: /usr/sbin/sshd -D
    volumes:
      - ssh-data:/root/.ssh
    ports:
      - 22
